language: node_js

node_js: stable

branches:
  except:
  - /.*/

branches:
  only:
  - source

env:
  global:
    secure: "zbvCFnMNQOkT7+UkywWmgI9ZESIfnomiNqm8habNJzYTWSqcD+3pqpq1pnIUYMGy3/2D92/fRRX/AQQsXP8Np/cVYZryiT343JRn3Te8RJbOi2yf6/Dm/Zhba3gbXNBNlIpV4vwPhQiqFXzT7kj0gCKyw7HAHsE5J5rnh9QgJ9H7kJlYnw7xSP4RYQbgcpao5Hi+HwLiw7WC9XTGzhpVhEskbmtyibCcTNnvShcqpYeQQVt30QIEHZCEaAczWn9aNFcvtrsF0Uoy6Cb/z2uGu3q0KQLHMjHYxyaFVgt0++7s/cXJ06A+PUkdRC5HTGhhl9Zxr0d7N98nwiAm3A8NysIfDQ1U/UEeaP4svJkQnTUp3ZSdj7bpjLoxHvVgbWeL2iBFLFTnVE32V2lVfSZrkgG+IUSdkGKId+q2lrtXEqe4bkxkuNIm9zyORsBSCSo9lbCHYM3n2C/Ka9JsYQGBLq8WCJyppv9bDREFUVKjoEOpzmobI95diQMAHxHS/AULRvOBNIBV870qAt+mTjBFPKgCoDLn7A7FgTKoAsKq4T1YMWoOKzs9/kiBKRzWeloAAE1UtyKVqCAA5nK6n5aQUUE4fow0/ChUtgH+Lxpp1ngYVEaCVi12fNViixPzXQS8z43lIOg2hYc1lcQn5jO6aaJpJwlXtAK3sCJkaN6jqoE="

before_install:
- npm install -g hexo-cli
- npm install

install:
- hexo generate

before_script:
- git config --global user.name 'Robert Peng'
- git config --global user.email 'robert.peng@foxmail.com'
- sed -i'' "s~git@github.com:Mr-Dai/Mr-Dai.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/Mr-Dai/Mr-Dai.github.io.git~" _config.yml

script:
- hexo deploy

notifications:
  email:
    recipients:
      - robert.peng@foxmail.com
    on_success: never
    on_failure: always
